# Configuraci칩n para Netlify

[build]
  command = "npm run build" # Comando para compilar el sitio para producci칩n
  publish = "dist"          # Directorio que se desplegar치

[dev]
  command = "vite"          # Comando para iniciar el servidor de desarrollo de Vite
  targetPort = 5173         # Puerto en el que Vite se ejecuta
  port = 8888               # Puerto en el que Netlify Dev estar치 disponible
