# Configuración para Netlify

[build]
  command = "npm run build && cp public/_redirects.prod dist/_redirects"
  publish = "dist"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  framework = "#static"
